[build-system]
requires = [
  "scikit-build-core @ https://github.com/scikit-build/scikit-build-core/archive/refs/heads/main.zip",
]
build-backend = "scikit_build_core.build"

[project]
name = "ogs"
version = "6.4.4.dev1"
# dynamic = ["version"]

[tool.scikit-build]
experimental = true
cmake.minimum-version = "3.22.0"
ninja.make-fallback = false
# metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

[tool.cmake]
build-dir = "build/{wheel_tag}"
cmake.args = ["--preset", "wheel", "-DOGS_BUILD_PROCESSES=SteadyStateDiffusion"]

[tool.pytest.ini_options]
testpaths = ["Tests"]
norecursedirs = ["Tests/Data"]

[tool.cibuildwheel]
archs = "auto64"
build = "cp3*"
test-extras = "test"
test-command = "pytest {project}/Tests/Python"
build-verbosity = "1"

[tool.cibuildwheel.linux]
skip = ["*musllinux*", "cp36-*"]
# See https://github.com/NixOS/patchelf/issues/446
# quay.io/pypa/manylinux_2_28 works too
manylinux-x86_64-image = "quay.io/pypa/manylinux2014_x86_64@sha256:005826a6fa94c97bd31fccf637a0f10621304da447ca2ab3963c13991dffa013"
manylinux-aarch64-image = "quay.io/pypa/manylinux2014_x86_64@sha256:005826a6fa94c97bd31fccf637a0f10621304da447ca2ab3963c13991dffa013"
before-all = "yum install -y ccache"
environment-pass = [
  "SETUPTOOLS_SCM_LOCAL_SCHEME",
  "CPM_SOURCE_CACHE",
  "CCACHE_DIR",
  "CCACHE_MAXSIZE",
  "CMAKE_ARGS",
]

[tool.cibuildwheel.macos]
skip = ["cp36-*", "cp37-*", "cp38-*x86_64"]

[tool.cibuildwheel.windows]
skip = ["cp36-*", "cp37-*"]
